Improve Logs for SQS crons
headout/ergo-kotlin pull request #18
Opened 2023-03-23 11:00 UTC by himanshudabas

Changes:
* Added the sqs message jobId as MDC to improve logs
* Added logs to track how much time crons are taking
* bumped version to 1.3.2

2023-06-26 14:24 UTC, podholadavid approved these changes

2023-06-27 11:16 UTC, strikertanmay approved these changes

2023-07-11 07:38 UTC, shahsurajk requested changes

2023-07-11 07:38 UTC, shahsurajk commented on local.properties
you have added `local.properties` on `.gitignore` and it's tracked here. you really wish to prevent it from being tracked, delete this file from git cache. `git rm --cached <file>`

2023-07-11 07:38 UTC, shahsurajk commented on ergo-service-sqs/src/main/kotlin/headout/oss/ergo/services/SqsMsgService.kt
> +                            Dispatchers.IO,
if we're really planning on revamping the SQS messaging, we should ideally remove Coroutines from this. Async + Async is never a good combination.

2023-07-11 07:38 UTC, shahsurajk commented on ergo-service-sqs/build.gradle.kts
> +                username = System.getenv("HEADOUT_REPOSITORY_USERNAME") ?: props.getProperty("headoutRepositoryUsername")
you should ideally publish a fat jar. @zkewal can help you on the same.

2023-07-11 07:39 UTC, himanshudabas commented on local.properties
i want the placeholder file to be present, but not commit future changes to the file (since those would probably be creds) how can I achieve that?

2023-07-11 07:52 UTC, himanshudabas commented on ergo-service-sqs/build.gradle.kts
> +                username = System.getenv("HEADOUT_REPOSITORY_USERNAME") ?: props.getProperty("headoutRepositoryUsername")
not related to the changes, but isn't fatjar suitable for cases where we need to bundle all the dependencies in the jar itself (usually when we require the application to run standalone), since this is a library all the required dependencies would anyway be provided by whoever is integrating this?

2023-07-11 07:57 UTC, shahsurajk approved these changes
LGTM

2023-07-11 09:51 UTC, merged